// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPP9jk2V2o-sRY15NVm3h-iskZNLli9kM',
    appId: '1:1030596549497:web:4933e345d662fcd001eda8',
    messagingSenderId: '1030596549497',
    projectId: 'storeai-57540',
    authDomain: 'storeai-57540.firebaseapp.com',
    storageBucket: 'storeai-57540.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANCoVs8oDkvhL1iRKNahG5dxn7dfTankw',
    appId: '1:1030596549497:android:fec9adef42d8d65101eda8',
    messagingSenderId: '1030596549497',
    projectId: 'storeai-57540',
    storageBucket: 'storeai-57540.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByXp5wK-pxf6NE0hc4jeZUWFxVX27sxnQ',
    appId: '1:1030596549497:ios:ebe92cb69d8ca84201eda8',
    messagingSenderId: '1030596549497',
    projectId: 'storeai-57540',
    storageBucket: 'storeai-57540.firebasestorage.app',
    iosBundleId: 'com.naji.storeAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByXp5wK-pxf6NE0hc4jeZUWFxVX27sxnQ',
    appId: '1:1030596549497:ios:ebe92cb69d8ca84201eda8',
    messagingSenderId: '1030596549497',
    projectId: 'storeai-57540',
    storageBucket: 'storeai-57540.firebasestorage.app',
    iosBundleId: 'com.naji.storeAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPP9jk2V2o-sRY15NVm3h-iskZNLli9kM',
    appId: '1:1030596549497:web:1480cc1f696d126301eda8',
    messagingSenderId: '1030596549497',
    projectId: 'storeai-57540',
    authDomain: 'storeai-57540.firebaseapp.com',
    storageBucket: 'storeai-57540.firebasestorage.app',
  );
}
